fix : sleep swarm

diff --git a/.github/workflows/ci-docker-compose.yml b/.github/workflows/ci-docker-compose.yml
--- a/.github/workflows/ci-docker-compose.yml
+++ b/.github/workflows/ci-docker-compose.yml
@@ -1,4 +1,4 @@
-name: Docker Compose CI
+name: Docker Swarm CI
 
 on:
   push:
@@ -26,11 +26,12 @@ jobs:
     - name: 🛡️ Lancer les services Suricata
       run: |
         docker stack deploy -c Suricata/docker-compose.yml suricata || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        sleep 10
 
-    # - name: ✅ Vérifier l'état de Suricata
-    #   run: |
-    #     docker service ls
-    #     docker service ps suricata || echo "TEST_FAILED=true" >> $GITHUB_ENV
+    - name: ✅ Vérifier l'état de Suricata
+      run: |
+        echo "Attente de la montée de Suricata..."
+        timeout 180 bash -c 'while [[ $(docker service ps suricata --format "{{.CurrentState}}" | grep -c "Running") -eq 0 ]]; do sleep 5; done' || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
     ###########################
     #         WAZUH          #
@@ -38,12 +39,14 @@ jobs:
     - name: 📊 Lancer les services Wazuh
       run: |
         docker stack deploy -c wazuh/docker-compose.yml wazuh || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        sleep 10
 
-    # - name: ✅ Vérifier l'état de Wazuh
-    #   run: |
-    #     docker service ls
-    #     curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
-    #     curl -f http://localhost:55000 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+    - name: ✅ Vérifier l'état de Wazuh
+      run: |
+        echo "Attente de la montée de Wazuh..."
+        timeout 180 bash -c 'while [[ $(docker service ps wazuh --format "{{.CurrentState}}" | grep -c "Running") -eq 0 ]]; do sleep 5; done' || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:55000 || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
     ###########################
     #          ELK           #
@@ -51,12 +54,14 @@ jobs:
     - name: 📈 Lancer les services ELK
       run: |
         docker stack deploy -c ELK/docker-compose.yml elk || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        sleep 10
 
-    # - name: ✅ Vérifier l'état de ELK
-    #   run: |
-    #     docker service ls
-    #     curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
-    #     curl -f http://localhost:9200 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+    - name: ✅ Vérifier l'état de ELK
+      run: |
+        echo "Attente de la montée de ELK..."
+        timeout 180 bash -c 'while [[ $(docker service ps elk --format "{{.CurrentState}}" | grep -c "Running") -eq 0 ]]; do sleep 5; done' || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:9200 || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
     ###########################
     #        OPENCTI         #
@@ -64,22 +69,14 @@ jobs:
     - name: 🔍 Lancer les services OpenCTI
       run: |
         docker stack deploy -c opencti/docker-compose.yml opencti || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        sleep 10
 
-    # - name: ✅ Vérifier l'état de OpenCTI
-    #   run: |
-    #     docker service ls
-    #     curl -f http://localhost:8080 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+    - name: ✅ Vérifier l'état de OpenCTI
+     run: |
+       echo "Attente de la montée de OpenCTI..."
+       timeout 180 bash -c 'while [[ $(docker service ps opencti --format "{{.CurrentState}}" | grep -c "Running") -eq 0 ]]; do sleep 5; done' || echo "TEST_FAILED=true" >> $GITHUB_ENV
+       curl -f http://localhost:8080 || echo "TEST_FAILED=true" >> $GITHUB_ENV
 
-
-    - name: ✅ Vérifier l'état global des services
-      id: tests
-      run: |
-        set -e
-        docker service ls
-        curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
-        curl -f http://localhost:9200 || echo "TEST_FAILED=true" >> $GITHUB_ENV
-        curl -f http://localhost:8080 || echo "TEST_FAILED=true" >> $GITHUB_ENV
-    
     ###########################
     #       NETTOYAGE        #
     ###########################
