feat : update ci-docker-compose

diff --git a/.github/workflows/ci-docker-compose.yml b/.github/workflows/ci-docker-compose.yml
--- a/.github/workflows/ci-docker-compose.yml
+++ b/.github/workflows/ci-docker-compose.yml
@@ -61,9 +61,42 @@ jobs:
     #     docker compose -f opencti/docker-compose.yml ps
     #     curl -f http://localhost:8080 || exit 1  # Vérifie l'interface OpenCTI
 
+    - name: ✅ Vérifier l'état des services
+      id: tests
+      run: |
+        set -e
+        docker compose -f wazuh/docker-compose.yml ps
+        docker compose -f ELK/Docker-compose.yml ps
+        docker compose -f opencti/docker-compose.yml ps
+        # Vérification des services
+        curl -f http://localhost:5601 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:9200 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+        curl -f http://localhost:8080 || echo "TEST_FAILED=true" >> $GITHUB_ENV
+
     - name: 🗑️ Nettoyer les services
       run: |
         docker compose -f Suricata/docker-compose.yml down
         docker compose -f wazuh/docker-compose.yml down
         docker compose -f ELK/Docker-compose.yml down
         docker compose -f opencti/docker-compose.yml down
+
+    # Gestion de la branche cible
+    - name: 🏷️ Déterminer la branche cible
+      id: branch_target
+      run: |
+        if [ -z "$TEST_FAILED" ]; then
+          echo "BRANCH=dev" >> $GITHUB_ENV
+        else
+          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
+          echo "BRANCH=erreur-$TIMESTAMP" >> $GITHUB_ENV
+        fi
+
+    # Création et push sur la bonne branche
+    - name: 🚀 Créer et Pousser la branche
+      run: |
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "github-actions@github.com"
+        git checkout -b ${{ env.BRANCH }}
+        git add .
+        git commit -m "Mise à jour automatique via GitHub Actions"
+        git push origin ${{ env.BRANCH }} --force
