feat : add exist files

diff --git a/.github/workflows/ci-docker-compose.yml b/.github/workflows/ci-docker-compose.yml
--- a/.github/workflows/ci-docker-compose.yml
+++ b/.github/workflows/ci-docker-compose.yml
@@ -19,14 +19,21 @@ jobs:
     - name: ⚙️ Configurer Docker et Swarm
       run: |
         docker swarm init || true
+    
+    - name: 🔎 Vérifier l'existence des fichiers
+      run: |
+        ls -l Suricata/docker-compose.yml || exit 1
+        ls -l wazuh/docker-compose.yml || exit 1
+        ls -l ELK/docker-compose.yml || exit 1
+        ls -l opencti/docker-compose.yml || exit 1
 
     ###########################
     #        SURICATA         #
     ###########################
-    # - name: 🛡️ Lancer les services Suricata
-    #   run: |
-    #     docker stack deploy -c Suricata/docker-compose.yml suricata || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
-    #     sleep 10
+    - name: 🛡️ Lancer les services Suricata
+      run: |
+        docker stack deploy -c Suricata/docker-compose.yml suricata || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        sleep 10
 
     # - name: ✅ Vérifier l'état de Suricata
     #   run: |
@@ -36,10 +43,10 @@ jobs:
     ###########################
     #         WAZUH          #
     ###########################
-    # - name: 📊 Lancer les services Wazuh
-    #   run: |
-    #     docker stack deploy -c wazuh/docker-compose.yml wazuh || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
-    #     sleep 10
+    - name: 📊 Lancer les services Wazuh
+      run: |
+        docker stack deploy -c wazuh/docker-compose.yml wazuh || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        sleep 10
 
     # - name: ✅ Vérifier l'état de Wazuh
     #   run: |
