fix : delete exit 1

diff --git a/.github/workflows/ci-docker-compose.yml b/.github/workflows/ci-docker-compose.yml
--- a/.github/workflows/ci-docker-compose.yml
+++ b/.github/workflows/ci-docker-compose.yml
@@ -32,7 +32,7 @@ jobs:
     ###########################
     - name: 🛡️ Lancer les services Suricata
       run: |
-        docker stack deploy -c Suricata/Docker-compose.yml suricata || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        docker stack deploy -c Suricata/Docker-compose.yml suricata || echo "TEST_FAILED=true" >> $GITHUB_ENV
         sleep 10
 
     # - name: ✅ Vérifier l'état de Suricata
@@ -45,7 +45,7 @@ jobs:
     ###########################
     - name: 📊 Lancer les services Wazuh
       run: |
-        docker stack deploy -c wazuh/docker-compose.yml wazuh || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        docker stack deploy -c wazuh/docker-compose.yml wazuh || echo "TEST_FAILED=true" >> $GITHUB_ENV
         sleep 10
 
     # - name: ✅ Vérifier l'état de Wazuh
@@ -60,7 +60,7 @@ jobs:
     ###########################
     - name: 📈 Lancer les services ELK
       run: |
-        docker stack deploy -c ELK/Docker-compose.yml elk || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        docker stack deploy -c ELK/Docker-compose.yml elk || echo "TEST_FAILED=true" >> $GITHUB_ENV
         sleep 10
 
     # - name: ✅ Vérifier l'état de ELK
@@ -75,7 +75,7 @@ jobs:
     ###########################
     - name: 🔍 Lancer les services OpenCTI
       run: |
-        docker stack deploy -c opencti/docker-compose.yml opencti || (echo "TEST_FAILED=true" >> $GITHUB_ENV && exit 1)
+        docker stack deploy -c opencti/docker-compose.yml opencti || echo "TEST_FAILED=true" >> $GITHUB_ENV
         sleep 10
 
     # - name: ✅ Vérifier l'état de OpenCTI
